version: '3'

services:
  gophermart-postgres:
    image: postgres:latest
    container_name: gophermart-postgres
    environment:
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - gophermart_data:/var/lib/postgresql/data
volumes:
  gophermart_data:
